#!/bin/sh

# 1. 忽略 PPPoE 和 IPv6 获取的运营商 DNS
uci -q set network.wan.peerdns='0'
uci -q set network.wan6.peerdns='0'

# 2. dnsmasq 不读取 resolv.conf
uci -q set dhcp.@dnsmasq[0].noresolv='1'

# 3. 只使用指定的上游 DNS
uci -q delete dhcp.@dnsmasq[0].server
uci add_list dhcp.@dnsmasq[0].server='180.76.76.76'
uci add_list dhcp.@dnsmasq[0].server='223.5.5.5'

# 4. ★关键★ 不在 RA 中通告 IPv6 DNS（彻底解决 fe80 DNS）
# 引用来源：odhcpd 配置文档，正确参数为 dns_service 设为 0。ra_dns 是无效参数。
uci -q set dhcp.lan.dns_service='0'
uci -q delete dhcp.lan.dns

# 5. 保证 IPv6 前缀正常下发
uci -q set dhcp.lan.ra='server'
uci -q set dhcp.lan.dhcpv6='server'
uci -q set dhcp.lan.ndp='hybrid'

# 6. DNS 性能参数
uci -q set dhcp.@dnsmasq[0].cachesize='2000'
uci -q set dhcp.@dnsmasq[0].allservers='1'

uci commit

exit 0